#ifndef FIRELITE_H
#define FIRELITE_H

#pragma once

/* Auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define INSERT 1

#define DELETE 2

#define DEFAULT_PAGE_SIZE 4096

typedef struct FireLiteHandle FireLiteHandle;

struct FireLiteHandle *firelite_open(const char *path);

void firelite_close(struct FireLiteHandle *handle);

int32_t firelite_put_json(struct FireLiteHandle *handle,
                          const char *collection,
                          const char *doc_id,
                          const char *json);

char *firelite_get_json(struct FireLiteHandle *handle, const char *collection, const char *doc_id);

int32_t firelite_delete(struct FireLiteHandle *handle, const char *collection, const char *doc_id);

const char *firelite_last_error_message(struct FireLiteHandle *handle);

void firelite_free_string(char *value);

#endif  /* FIRELITE_H */
