#ifndef FIRELITE_H
#define FIRELITE_H

#pragma once

/* Auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define INSERT 1

#define DELETE 2

#define DEFAULT_PAGE_SIZE 4096

typedef struct FL_Batch FL_Batch;

typedef struct FL_Doc FL_Doc;

typedef struct FL_Engine FL_Engine;

typedef struct FL_Query FL_Query;

struct FL_Engine *fl_engine_open(const char *path);

void fl_engine_free(struct FL_Engine *engine);

struct FL_Doc *fl_doc_new(void);

void fl_doc_free(struct FL_Doc *doc);

int32_t fl_doc_insert_str(struct FL_Doc *doc, const char *key, const char *value);

int32_t fl_doc_insert_int(struct FL_Doc *doc, const char *key, int64_t value);

int32_t fl_doc_insert_float(struct FL_Doc *doc, const char *key, double value);

int32_t fl_doc_insert_bool(struct FL_Doc *doc, const char *key, bool value);

int32_t fl_doc_insert_null(struct FL_Doc *doc, const char *key);

int32_t fl_doc_insert_bin(struct FL_Doc *doc, const char *key, const uint8_t *data, uintptr_t len);

int32_t fl_engine_insert(struct FL_Engine *engine,
                         const char *collection,
                         const char *doc_id,
                         const struct FL_Doc *doc);

struct FL_Doc *fl_engine_get(struct FL_Engine *engine, const char *collection, const char *doc_id);

int32_t fl_engine_delete(struct FL_Engine *engine, const char *collection, const char *doc_id);

struct FL_Batch *fl_batch_new(void);

void fl_batch_free(struct FL_Batch *batch);

int32_t fl_batch_set(struct FL_Batch *batch,
                     const char *collection,
                     const char *doc_id,
                     const struct FL_Doc *doc);

int32_t fl_batch_delete(struct FL_Batch *batch, const char *collection, const char *doc_id);

int32_t fl_batch_commit(struct FL_Engine *engine, struct FL_Batch *batch);

struct FL_Query *fl_query_new(const char *collection);

void fl_query_free(struct FL_Query *query);

int32_t fl_query_where_eq_str(struct FL_Query *query, const char *field, const char *value);

int32_t fl_query_where_eq_int(struct FL_Query *query, const char *field, int64_t value);

int32_t fl_query_order_by(struct FL_Query *query, const char *field, bool ascending);

int32_t fl_query_limit(struct FL_Query *query, uintptr_t limit);

char *fl_query_execute(struct FL_Engine *engine, const struct FL_Query *query);

char *fl_doc_to_json(const struct FL_Doc *doc);

const char *fl_last_error(void);

void fl_string_free(char *value);

#endif  /* FIRELITE_H */
